name: Build
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:

          - name: "JVM"
            os: "ubuntu-latest"
            image: "gradle"
            compileTask: "compileKotlinJvm"
            testTask: "jvmTest"

          - name: "JS"
            os: "ubuntu-latest"
            image: "gradle"
            compileTask: "compileKotlinJS"
            testTask: "jsTest"

    runs-on: ${{ matrix.platform.os }}
    container:
      image: ${{ matrix.platform.image }}
    name: ${{ matrix.platform.name }}
    steps:

      - name: Checkout Repository
        uses: "actions/checkout@v2"

      - name: Start Gradle Daemon
        run: "gradle clean"

      - name: Compile Project
        run: "gradle ${{ matrix.platform.compileTask }}"

      - name: Test Project
        run: "gradle ${{ matrix.platform.testTask }}"
